all:
	gcc main.c stb_image_sources/stb/stb_image.h stb_image_sources/stb/stb_image_write.h image_rotation.c -o main -lm
c:
	gcc main.c stb_image_sources/stb/stb_image.h stb_image_sources/stb/stb_image_write.h image_rotation.c -o main -lm
